version: '3.8'

services:
  rabbit_python_receiver:
    container_name: rabbit_python
    env_file:
      - .env
    build:
      context: ./app
      target: receiver_runtime
    depends_on:
      - rabbit_0
      - rabbit_1
      - rabbit_2
    volumes:
      - ./app:/app
    networks:
      - rabbits
  
  rabbit_python_sender:
    container_name: rabbit_python
    env_file:
      - .env
    build:
      context: ./app
      target: sender_runtime
    depends_on:
      - rabbit_0
      - rabbit_1
      - rabbit_2
    volumes:
      - ./app:/app
    networks:
      - rabbits

  rabbit_1:
    container_name: rabbit_1
    image: rabbitmq:3.11-management
    hostname: rabbit_1
    env_file:
      - .env
    volumes:
      - ./config/rabbit_1/:/config/
    ports:
      - 15672:15672
    networks:
      - rabbits

  rabbit_2:
    container_name: rabbit_2
    image: rabbitmq:3.11-management
    hostname: rabbit_2
    env_file:
      - .env
    volumes:
      - ./config/rabbit_2/:/config/
    ports:
      - 15673:15672
    networks:
      - rabbits

  rabbit_3:
    container_name: rabbit_3
    image: rabbitmq:3.11-management
    hostname: rabbit_3
    env_file:
      - .env
    volumes:
      - ./config/rabbit_3/:/config/
    ports:
      - 15674:15672
    networks:
      - rabbits

networks:
  rabbits:
    driver: bridge
