version: '3.8'

services:
  rabbit-1:
    container_name: rabbit-1
    image: rabbitmq:3.11-management
    hostname: rabbit-1
    env_file:
      - .env
    volumes:
      - ./config/rabbit-1/:/config/
    ports:
      - 15672:15672
    networks:
      - rabbits

  rabbit-2:
    container_name: rabbit-2
    image: rabbitmq:3.11-management
    hostname: rabbit-2
    env_file:
      - .env
    volumes:
      - ./config/rabbit-2/:/config/
    ports:
      - 15673:15672
    networks:
      - rabbits

  rabbit-3:
    container_name: rabbit-3
    image: rabbitmq:3.11-management
    hostname: rabbit-3
    env_file:
      - .env
    volumes:
      - ./config/rabbit-3/:/config/
    ports:
      - 15674:15672
    networks:
      - rabbits

networks:
  rabbits:
    driver: bridge
